name: Project Erebus CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:latest
        env:
          NEO4J_AUTH: neo4j/erebuspassword
        ports:
          - 7687:7687
          - 7474:7474

    steps:
    - uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Bağımlılıkları Yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Testleri Otomatik Koştur
      run: |
        pytest